---
layout: default
modal-id: 3
img: 
alt: image-alt
project-date: 17/12/2017
author: Lê Thị Quỳnh Nhi
category: community
---

#### SUNDAY CÀFE

##### Cafe sinh thống kê - chuỗi sinh hoạt thân mật, gặp gỡ với Bs. Phùng Khánh Lâm, Tiến sĩ Thống kê y sinh học. Lịch thường được set mỗi 2- 3 tuần. Nếu bạn có câu hỏi, có thể đặt ở đây, hoặc ghé thăm website của chúng tôi, xanhfoundation.org

##### Café skills training  (Công tác xã hội; 10/12)

#### Xanh Fellowship 
##### Professional development 
Chúng tôi hỗ trợ tư vấn chuyên môn cho người thực hiện nghiên cứu lâm sàng, nghiên cứu y tế công cộng, quản lý nghiên cứu, thực hiện nghiên cứu. 
Các bạn chuẩn bị đề tài tốt nghiệp đại học và sau đại học được khuyến khích nộp đề cương về cho chúng tôi ( xanhfoundation@gmail.com).
Với các kinh nghiệm thực tế trong quá trình thực hiện và quản lý nghiên cứu, chúng tôi muốn hỗ trợ các bạn khác trong thời gian đầu sự nghiệp nghiên cứu trong lĩnh vực sức khoẻ con người.

##### Bike cycle 
Học bổng với Xanh Foundation - Xe cộ
Chúng tôi hỗ trợ các bạn sinh viên hoặc bạn mới ra trường phương tiện đi lại. 
- Cho: Nếu bạn có xe (đạp, máy) không dùng đến nữa, nhưng không muốn bán đi, hãy cùng chúng tôi trao đến cho người đang cần. Họ sẽ được yêu cầu sử dụng và bảo quản tài sản cho bạn.
- Nhận: Nếu bạn muốn nhận xe, hãy email cho chúng tôi (xanhfoudation@gmail.com) hoặc ghé thăm website của chúng tôi, xanhfoundation.org , cho chúng tôi biết vì sao bạn cần (qua 1 bài luận tự viết và đề xuất 1 người tham khảo).
